services:
  back_database:
    image: pgvector/pgvector:pg16
    volumes:
      - backData:/var/lib/postgresql/data
      - ./back_conectee/scripts/database.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: conectee
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5434"
  conectee_app:
    image: back_conectee
    build: back_conectee
    ports:
      - "8080:8080"
    depends_on:
      - back_database
    env_file:
      - back_database/.env
volumes:
  backData: