[tool.poetry]
name = "back-end-simcc"
version = "3.0.0"
description = ""
authors = ["meirelesgc <geu_costa@outlook.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9.2"
zeep = "^4.2.1"
nltk = "^3.9.1"
unidecode = "^1.3.8"
flask = "^3.0.3"
flask-cors = "^5.0.0"
python-dotenv = "^1.0.1"
psycopg2-binary = "^2.9.9"
pandas = "^2.2.3"
langchain-openai = "^0.2.0"
beautifulsoup4 = "^4.12.3"
gunicorn = "^23.0.0"
firebase-admin = "^6.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
